### ISSUE TITLE
dist目录下生成的amd.js引用后无效果

### ISSUE THREAD

**Issue by 20170101** [Yuliang-Lee/webpack-libraryTarget-demo#1]
xlaoyu 大神：
我下载webpack-libraryTarget-demo后在dist下新建了一个html，内容如下：
head标签中引用：    <script src="https://cdn.bootcss.com/require.js/2.3.6/require.js"></script>
然后body标签中添加如下代码：
<script>
        require(['amd.js'], function(myDemo) {
            myDemo.a();
        });
    </script>

可是用浏览器打开这个html后console报错：
Uncaught TypeError: Cannot read property 'a' of undefined
恳请大神指教，感激不尽

**Comment by Yuliang-Lee** [comment]
这是一个怎么使用 require.js 的问题，不是库的问题
